---
# Dane publiczne serwera Proxmox
pve_api_host: "172.26.165.52"
pve_api_user: "root@pam!ansible-token-bitwarden-deploy" # Format: użytkownik@realm!identyfikator_tokenu

# Konfiguracja nowej VM
vmid: "120"
vm_name: "bitwarden-prod"
template_name: "debian-12-template"
node: "pve"
target_vm_ip: "172.26.165.235"

# Konfiguracja aplikacji
domain_name: "bitwarden.mroczkowscy.eu"
ssl_email: "grzegorz.mroczkowski@mroczkowscy.eu"